name: Deploy Static Website to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
        
    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm install
        fi
        
    - name: Build static site (if build script exists)
      run: |
        if [ -f package.json ] && npm run | grep -q "build"; then
          npm run build
        fi
        
    - name: Sync files to S3
      run: |
        # Determine source directory - use build output if it exists, otherwise current directory
        if [ -d "dist" ]; then
          SOURCE_DIR="dist"
        elif [ -d "build" ]; then
          SOURCE_DIR="build"
        else
          SOURCE_DIR="."
        fi
        
        aws s3 sync $SOURCE_DIR s3://${{ secrets.AWS_S3_BUCKET || 'your-bucket-name' }} \
          --delete \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "node_modules/*" \
          --exclude "*.md" \
          --exclude "*.docx"